/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Usuario;

import Connection.ConnectionFactory;
import CrudQuestoes.TelaInicialAdm;
import java.awt.Cursor;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import telaInicial.EfeitoSonoro;

/**
 *
 * @author felip
 */
public class CrudUsuarios extends javax.swing.JFrame {
    private int indexSelecionado = -1;
    private UsuarioTableModel tabelaUsuario = new UsuarioTableModel();
    /**
     * Creates new form ManterUsuarios
     */
    public CrudUsuarios() {
        initComponents();
        JTableUsuarios.setModel(tabelaUsuario);
        getUsuarios();
        txtEmail.setOpaque(false);
        txtNome.setOpaque(false);
        txtSenha.setOpaque(false);
        setLocationRelativeTo(null);
    }

    private void getUsuarios() {
        try
        {
            while (this.tabelaUsuario.getRowCount() > 0) {
                this.tabelaUsuario.removeRow(0);
            }

            for (Usuario usuario : UsuarioService.get()) {
                this.tabelaUsuario.addRow(usuario);
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro ao carregar usuários", JOptionPane.ERROR_MESSAGE);
        }
    }
    public static boolean usuarioExiste(String nomeUsuario) throws Exception {
        String query = "SELECT COUNT(*) FROM Jogador WHERE nomeJogador = ?";
        try (Connection conn = ConnectionFactory.obterConexao();
             PreparedStatement stmt = conn.prepareStatement(query)) {
            stmt.setString(1, nomeUsuario);
            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    return rs.getInt(1) > 0;
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return false;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JTableUsuarios = new javax.swing.JTable();
        txtNome = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        voltarBotao = new javax.swing.JButton();
        loginTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtSenha = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        ButSalvar = new javax.swing.JButton();
        ButAlterar = new javax.swing.JButton();
        ButRemover = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JTableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTableUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTableUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTableUsuarios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 520, 150));

        txtNome.setBackground(new java.awt.Color(0,0,0,1));
        txtNome.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtNome.setForeground(new java.awt.Color(255, 255, 255));
        txtNome.setBorder(null);
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 420, 20));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 420, 10));

        voltarBotao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        voltarBotao.setForeground(new java.awt.Color(255, 255, 255));
        voltarBotao.setText("< Voltar");
        voltarBotao.setBorder(null);
        voltarBotao.setContentAreaFilled(false);
        voltarBotao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voltarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarBotaoActionPerformed(evt);
            }
        });
        getContentPane().add(voltarBotao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        loginTitulo.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 40)); // NOI18N
        loginTitulo.setForeground(new java.awt.Color(255, 255, 255));
        loginTitulo.setText("EDITAR USUÁRIOS");
        getContentPane().add(loginTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Senha:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 50, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 420, 10));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 50, -1));

        txtEmail.setBackground(new java.awt.Color(0,0,0,1));
        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setBorder(null);
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 181, 420, 20));

        txtSenha.setBackground(new java.awt.Color(0,0,0,1));
        txtSenha.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtSenha.setForeground(new java.awt.Color(255, 255, 255));
        txtSenha.setBorder(null);
        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 420, 20));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 420, 10));

        ButSalvar.setBackground(new java.awt.Color(6, 16, 6));
        ButSalvar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButSalvar.setForeground(new java.awt.Color(255, 255, 255));
        ButSalvar.setText("Salvar");
        ButSalvar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        ButSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(ButSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, 100, 30));

        ButAlterar.setBackground(new java.awt.Color(6, 16, 6));
        ButAlterar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButAlterar.setForeground(new java.awt.Color(255, 255, 255));
        ButAlterar.setText("Atualizar");
        ButAlterar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        ButAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(ButAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 480, 100, 30));

        ButRemover.setBackground(new java.awt.Color(6, 16, 6));
        ButRemover.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButRemover.setForeground(new java.awt.Color(255, 255, 255));
        ButRemover.setText("Remover");
        ButRemover.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        ButRemover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButRemoverActionPerformed(evt);
            }
        });
        getContentPane().add(ButRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 480, 100, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_telas/adm2.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButSalvarActionPerformed
        EfeitoSonoro.Play("click.wav");
        ButSalvar.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        String nome = txtNome.getText();
        boolean validacao = true;
        try {
            if (!usuarioExiste(nome)) {
                
                Usuario u = new Usuario(nome, txtEmail.getText(), txtSenha.getText());
                validacao = false;

                UsuarioService.insert(u);

                // Adicionar mensagem de sucesso
                JOptionPane.showMessageDialog(this, "Usuário criado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

                this.getUsuarios();
                limparCampos();
            } else {
                JOptionPane.showMessageDialog(this, "Usuário já existe", "Aviso", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {
            String title = validacao ? "Validação" : "Erro";
            int pane = validacao ? JOptionPane.INFORMATION_MESSAGE : JOptionPane.ERROR_MESSAGE;

            JOptionPane.showMessageDialog(this, e.getMessage(), title, pane);
        }

    }//GEN-LAST:event_ButSalvarActionPerformed

    private void ButRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButRemoverActionPerformed
EfeitoSonoro.Play("click.wav");

if (this.indexSelecionado == -1)
    return;

try
{
    ButRemover.setCursor(new Cursor(Cursor.WAIT_CURSOR));
    Usuario u = this.tabelaUsuario.getUsuario(this.indexSelecionado);
    UsuarioService.delete(u);

    this.tabelaUsuario.removeRow(this.indexSelecionado);
    this.limparCampos();
    
    // Adiciona a mensagem de sucesso
    JOptionPane.showMessageDialog(this, "O usuário foi removido com sucesso.", "Usuário Removido", JOptionPane.INFORMATION_MESSAGE);
}
catch (Exception e)
{
    JOptionPane.showMessageDialog(this, e.getMessage(), "Erro ao deletar usuário", JOptionPane.ERROR_MESSAGE);
}

    }//GEN-LAST:event_ButRemoverActionPerformed

    private void ButAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButAlterarActionPerformed
EfeitoSonoro.Play("click.wav");
if (indexSelecionado == -1) {
    ButAlterar.setCursor(new Cursor(Cursor.WAIT_CURSOR));
    return;
}

boolean validacao = true;
try {
    Usuario u = this.tabelaUsuario.getUsuario(this.indexSelecionado);
    u.setNome(this.txtNome.getText());
    u.setEmail(this.txtEmail.getText());
    u.setSenha(this.txtSenha.getText());
    validacao = false;

    UsuarioService.update(u);
    this.tabelaUsuario.atualizar(u, this.indexSelecionado);

    // Adicionar mensagem de sucesso
    JOptionPane.showMessageDialog(this, "Usuário alterado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

    this.limparCampos();
} catch (Exception e) {
    String title = validacao ? "Validação" : "Erro";
    int pane = validacao ? JOptionPane.INFORMATION_MESSAGE : JOptionPane.ERROR_MESSAGE;

    JOptionPane.showMessageDialog(this, e.getMessage(), title, pane);
}


    }//GEN-LAST:event_ButAlterarActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
       EfeitoSonoro.Play("text.wav");
    }//GEN-LAST:event_txtNomeActionPerformed

    private void JTableUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableUsuariosMouseClicked
        // TODO add your handling code here:
        Usuario u = tabelaUsuario.getUsuario(JTableUsuarios.getSelectedRow());

        txtNome.setText(u.getNome());
        txtEmail.setText(u.getEmail());
        txtSenha.setText(u.getSenha());

        indexSelecionado = JTableUsuarios.getSelectedRow();
    }//GEN-LAST:event_JTableUsuariosMouseClicked

    private void voltarBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarBotaoActionPerformed
        EfeitoSonoro.Play("back.wav");
        TelaInicialAdm mq = new TelaInicialAdm();
        mq.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltarBotaoActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        EfeitoSonoro.Play("text.wav");
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        EfeitoSonoro.Play("text.wav");
    }//GEN-LAST:event_txtSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    private void limparCampos()
    {
        txtNome.setText("");
        txtEmail.setText("");
        txtSenha.setText("");
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrudUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrudUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrudUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrudUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrudUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButAlterar;
    private javax.swing.JButton ButRemover;
    private javax.swing.JButton ButSalvar;
    private javax.swing.JTable JTableUsuarios;
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel loginTitulo;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JButton voltarBotao;
    // End of variables declaration//GEN-END:variables
}
